version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/referrals
    command: nodemon src/index.js
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"